SELECT HISTORY_ID, CAR_ID,
    DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE,
    DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    IF (DATEDIFF(END_DATE, START_DATE) + 1 >= 30, '장기 대여', '단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') = "2022-09"
# WHERE LEFT(START_DATE, 7) = "2022-09" # => 날짜 데이터를 다루고 있으므로 DATE_FORMAT을 사용하여 의도를 나타내는게 더 좋을 것 같다고 판단
ORDER BY HISTORY_ID DESC